# Generated by Django 5.0.3 on 2024-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount_of_dislikes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='amount_of_likes',
            field=models.IntegerField(blank=True),
        ),
    ]
