# Generated by Django 5.0.3 on 2024-03-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_post_amount_of_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amount_of_dislikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='amount_of_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
