# Generated by Django 5.0.3 on 2024-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_profile_delete_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
