# Generated by Django 5.0.3 on 2024-03-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0016_alter_comment_amount_of_dislikes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='amount_of_dislikes',
            new_name='amount_of_comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='amount_of_dislikes',
        ),
    ]
