# Generated by Django 5.0.3 on 2024-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0017_rename_amount_of_dislikes_post_amount_of_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='social_app.profile'),
        ),
    ]
