# Generated by Django 5.0.3 on 2024-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0020_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to='social_app.profile'),
        ),
    ]
